language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
script: echo "We don't have tests yet :("
before_deploy:
  - sh config.sh
  - sh package.sh
deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: CE7soXxOfgwqzlfd8Z+wGwA8NKbZ3ACIy9ZzJRLC3ki8isj969jIeFnOte7NqQSrzPVyoT0j7Tt860ZcXR2gxAxOjXFJOoaWXf2A2ivH2FJY1+JEa5c5LE2JLFRH03tGyJYGY9lwqFU8hZKA8fVmSxA1Gh26lJFdq9kWupDePaCexaVEjvMytPsnZfc3tuBdLotGG6h3BxQxV3juMkM7dojFrcZD8rXFKLtU2XwoXdhC13riWBVtBbY0IO4wa4WjIOJ/2QkESq3KYbmXp+mVxq5yppfxQThSgPAUhKmd884m7TXt/LgtuOPl3DS45eTgrWtF7Am8JtXtc5MDlDjFClW7WAiEC5144zvZZoh4x+N6eR3DFAoU77RS4dsuhjW0UVm890Qr3jn9ngYbzC7MAFO6kN8WiYWLz75C8P6cpuZtxX+LFUNAV5XIIXBLVkhDl10C1rJ4LIuE2TN3MGOy37eqcuJLLfstjM7RI5QKw7a2UbrP+nBkUcQkngx0KP1g9895+Ixdi/Iyumfl2Gd0rNAR1UL0GULvr5/wJT4lJfBGybwynAjDTvoOtdk3LkMuI28mxHKVxHw6iIi9FBCax8EMqYt8k/iikyyAAAKBSwPn5pqg/tUphXm2K7xDrjd9iwVSLD4jEY5VVugKoEMeCfoAVtoZuUpcXVmvyIs1AkI=
  file: plugin-transbank-webpay-opencart3-$TRAVIS_TAG.ocmod.zip
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-opencart-webpay
    tags: true
